import { UiFeedbackLevel, UiSubLevel } from '@app/shared/types/ui-level';

/** Unique identifier of a toast message (auto-generated when omitted). */
export type UiToastId = string | number;

/**
 * Where a {@link UiToastContainer} pins its stack in the viewport.
 */
export type UiToastPosition =
  | 'top-left'
  | 'top-center'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right'
  | 'center';

/** All positions, in declaration order (handy for stories/docs). */
export const UI_TOAST_POSITIONS: readonly UiToastPosition[] = [
  'top-left',
  'top-center',
  'top-right',
  'bottom-left',
  'bottom-center',
  'bottom-right',
  'center',
];

/**
 * A single toast message pushed through the {@link UiToastService}.
 *
 * Only `title`/`text` are typically needed; everything else has a sensible
 * default resolved by the container.
 * remapped to this design system's semantic `level` / `subLevel` vocabulary.
 */
export interface UiToastMessage {
  /** Unique id. Auto-generated by the service when omitted. */
  id?: UiToastId;
  /** Routes the message to the container(s) sharing the same `key`. */
  key?: string;
  /** Semantic level (drives colours + default icon). */
  level?: UiFeedbackLevel;
  /** Hierarchical intensity (`high` = solid, `low` = subtle). */
  subLevel?: UiSubLevel;
  /** Bold heading line. */
  title?: string;
  /** Supporting body line. */
  text?: string;
  /**
   * Leading icon: a FontAwesome name to override the level default, `false`
   * to hide it, or omit / `true` for the level's default icon.
   */
  icon?: string | boolean;
  /** Show the dismiss button (default `true`). */
  closable?: boolean;
  /** Never auto-dismiss — the user must close it (default `false`). */
  sticky?: boolean;
  /** Auto-dismiss delay in ms. Falls back to the container `life`. */
  life?: number;
  /** Arbitrary payload forwarded to a custom `template` (custom / action toasts). */
  data?: unknown;
  /** Extra class(es) applied to the toast card for one-off styling. */
  styleClass?: string;
}

/** Context object handed to a container's custom content `template`. */
export interface UiToastTemplateContext {
  /** The message being rendered. */
  $implicit: UiToastMessage;
  /** Dismisses this toast (same as clicking the close button). */
  closeFn: () => void;
}

/** Default leading icon per semantic level (FontAwesome names, from the Figma source). */
export const UI_TOAST_DEFAULT_ICONS: Record<UiFeedbackLevel, string> = {
  default: 'info-circle',
  highlight: 'info-circle',
  success: 'check',
  warning: 'warning',
  error: 'times',
};
