import { ApplicationConfig, provideZonelessChangeDetection } from '@angular/core';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';
import { brandFromSubdomain, provideUiKitBrand } from '@4sh/ui-kit/theming';
import { provideUiImageAssets, UiImageAssetsMap } from '@4sh/ui-kit/ui-image';
import assetsMap from '../assets/assets-map.json';
import { routes } from './app.routes';

/**
 * Detect the active brand from the first subdomain segment.
 * e.g. themeone.localhost → 'themeone', themetwo.app.com → 'themetwo'.
 * Passed to the kit via `provideUiKitBrand()`: `BrandService` then applies it on
 * <html> via the `[data-brand]` attribute, which switches the generated
 * `--primitives-*` tokens. Detecting the brand stays an application concern —
 * the kit only consumes the result. Fallback: 'themeone'.
 */
const regex = /(?:https?:\/\/)?([-\w]*)\..*/;
const match = typeof window !== 'undefined' ? regex.exec(window.location.href) : null;
export const subdomain = match ? match[1] : 'themeone';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideHttpClient(withFetch()),
    provideRouter(routes),
    provideAnimations(),
    provideUiKitBrand(brandFromSubdomain(subdomain)),
    // Generated by `npm run generate:assets` — the kit can't know a project's assets.
    provideUiImageAssets(assetsMap as UiImageAssetsMap),
  ],
};
